# Configuracion del servidor local de LanguageTool
# Para activar los n-gramas en espanol, copiar la carpeta "ngrams" junto a esta
# y descomentar la linea siguiente (la ruta es relativa a la carpeta LanguageTool):
# languageModel=../ngrams
cacheSize=1000
pipelineCaching=true
maxPipelinePoolSize=500
